name: Rust Format
description: Check rustfmt formatting

inputs:
  package_name:
    description: "Optional package name to build"
    required: false

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        cargo fmt --all --check \
          ${{ inputs.package_name && format('-p {0}', inputs.package_name) || '' }}
