name: Rust Setup
description: Setup Rust toolchain (and optional Python)

inputs:
  python_version:
    description: "Custom python version to install (optional)"
    required: false
    default: ""

runs:
  using: composite
  steps:
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - if: inputs.python_version != ''
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}
